// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';

export function AddBatch(arg1:models.Batch,arg2:number,arg3:string):Promise<models.Batch>;

export function AddMedicine(arg1:models.Medicine,arg2:number,arg3:string):Promise<models.Medicine>;

export function AddSupplier(arg1:models.Supplier,arg2:number,arg3:string):Promise<models.Supplier>;

export function AdjustStock(arg1:number,arg2:any,arg3:number,arg4:string,arg5:number,arg6:string,arg7:string):Promise<void>;

export function ArchiveMedicine(arg1:number,arg2:boolean,arg3:number,arg4:string):Promise<void>;

export function CreateUser(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.User>;

export function ExportDatabase(arg1:string,arg2:number,arg3:string):Promise<void>;

export function GetBatchesByMedicine(arg1:number):Promise<Array<models.Batch>>;

export function GetDashboardSummary():Promise<services.DashboardSummary>;

export function GetExpiringBatches(arg1:number):Promise<Array<models.Batch>>;

export function ListAuditLogs(arg1:number):Promise<Array<models.AuditLog>>;

export function ListMedicines(arg1:string,arg2:string,arg3:boolean):Promise<Array<models.Medicine>>;

export function ListPurchases():Promise<Array<models.Purchase>>;

export function ListRecentSales(arg1:number):Promise<Array<models.Sale>>;

export function ListSuppliers():Promise<Array<models.Supplier>>;

export function ListUsers():Promise<Array<models.User>>;

export function Login(arg1:string,arg2:string):Promise<models.User>;

export function ProcessSale(arg1:number,arg2:string,arg3:Array<services.CartItemInput>,arg4:string):Promise<models.Sale>;

export function RecordPurchase(arg1:string,arg2:any,arg3:Array<services.IncomingStockItem>,arg4:string,arg5:number,arg6:string):Promise<models.Purchase>;

export function RestoreDatabase(arg1:string,arg2:number,arg3:string):Promise<void>;

export function UpdateMedicine(arg1:models.Medicine,arg2:number,arg3:string):Promise<void>;

export function UpdateSupplier(arg1:models.Supplier,arg2:number,arg3:string):Promise<void>;
