// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddBatch'](arg1, arg2, arg3);
}

export function AddMedicine(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddMedicine'](arg1, arg2, arg3);
}

export function AddSupplier(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddSupplier'](arg1, arg2, arg3);
}

export function AdjustStock(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AdjustStock'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ArchiveMedicine(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ArchiveMedicine'](arg1, arg2, arg3, arg4);
}

export function ArchiveSupplier(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ArchiveSupplier'](arg1, arg2, arg3, arg4);
}

export function AutoDiscoverServer() {
  return window['go']['main']['App']['AutoDiscoverServer']();
}

export function BulkImportMedicines(arg1, arg2, arg3) {
  return window['go']['main']['App']['BulkImportMedicines'](arg1, arg2, arg3);
}

export function ChangePassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2, arg3);
}

export function AdminResetPassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['AdminResetPassword'](arg1, arg2, arg3);
}

export function UnlockUser(arg1, arg2) {
  return window['go']['main']['App']['UnlockUser'](arg1, arg2);
}

export function CreatePrescription(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['CreatePrescription'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function CreateUser(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2, arg3, arg4, arg5);
}

export function DeactivateUser(arg1, arg2) {
  return window['go']['main']['App']['DeactivateUser'](arg1, arg2);
}

export function EnableMainServerMode(arg1) {
  return window['go']['main']['App']['EnableMainServerMode'](arg1);
}

export function ExportDatabase(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportDatabase'](arg1, arg2, arg3);
}

export function GetBatchesByMedicine(arg1) {
  return window['go']['main']['App']['GetBatchesByMedicine'](arg1);
}

export function GetCashierPerformance(arg1) {
  return window['go']['main']['App']['GetCashierPerformance'](arg1);
}

export function GetDashboardSummary() {
  return window['go']['main']['App']['GetDashboardSummary']();
}

export function GetExpiringBatches(arg1) {
  return window['go']['main']['App']['GetExpiringBatches'](arg1);
}

export function GetNetworkStatus() {
  return window['go']['main']['App']['GetNetworkStatus']();
}

export function GetNotificationsSummary() {
  return window['go']['main']['App']['GetNotificationsSummary']();
}

export function GetPrescriptionDetails(arg1) {
  return window['go']['main']['App']['GetPrescriptionDetails'](arg1);
}

export function GetSalesSummary() {
  return window['go']['main']['App']['GetSalesSummary']();
}

export function GetUserTodaySalesTotal(arg1) {
  return window['go']['main']['App']['GetUserTodaySalesTotal'](arg1);
}

export function GlobalSearch(arg1, arg2) {
  return window['go']['main']['App']['GlobalSearch'](arg1, arg2);
}

export function ListAuditLogs(arg1, arg2) {
  return window['go']['main']['App']['ListAuditLogs'](arg1, arg2);
}

export function ListMedicines(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListMedicines'](arg1, arg2, arg3);
}

export function ListMedicinesPaginated(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ListMedicinesPaginated'](arg1, arg2, arg3, arg4, arg5);
}

export function ListPrescriptions(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListPrescriptions'](arg1, arg2, arg3);
}

export function ListPurchaseItems(arg1) {
  return window['go']['main']['App']['ListPurchaseItems'](arg1);
}

export function ListPurchases() {
  return window['go']['main']['App']['ListPurchases']();
}

export function ListPurchasesPaginated(arg1, arg2) {
  return window['go']['main']['App']['ListPurchasesPaginated'](arg1, arg2);
}

export function ListRecentSales(arg1) {
  return window['go']['main']['App']['ListRecentSales'](arg1);
}

export function ListSuppliers(arg1) {
  return window['go']['main']['App']['ListSuppliers'](arg1);
}

export function ListUsers(arg1) {
  return window['go']['main']['App']['ListUsers'](arg1);
}

export function Login(arg1, arg2, arg3) {
  return window['go']['main']['App']['Login'](arg1, arg2, arg3);
}

export function Logout(arg1) {
  return window['go']['main']['App']['Logout'](arg1);
}

export function ProcessSale(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ProcessSale'](arg1, arg2, arg3, arg4);
}

export function RecordPurchase(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['RecordPurchase'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function ResetAndSeedDatabase(arg1) {
  return window['go']['main']['App']['ResetAndSeedDatabase'](arg1);
}

export function RestoreDatabase(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreDatabase'](arg1, arg2, arg3);
}

export function UpdateDatabaseConfig(arg1) {
  return window['go']['main']['App']['UpdateDatabaseConfig'](arg1);
}

export function UpdateMedicine(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateMedicine'](arg1, arg2, arg3);
}

export function UpdatePrescriptionStatus(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdatePrescriptionStatus'](arg1, arg2, arg3, arg4);
}

export function UpdateSupplier(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSupplier'](arg1, arg2, arg3);
}

export function UpdateUser(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateUser'](arg1, arg2, arg3, arg4);
}
